// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PerformanceTracker.Api.Data;

#nullable disable

namespace PerformanceTracker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907125120_NormalizeNonStaffSupervisors")]
    partial class NormalizeNonStaffSupervisors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PerformanceTracker.Api.Domain.ActivityLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EntraObjectId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StaffId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("SupervisorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SupervisorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SupervisorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.HasIndex("SupervisorUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.ArchivedStaffRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArchivedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OriginalUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StaffId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt");

                    b.HasIndex("Email");

                    b.ToTable("ArchivedStaff");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.FocusArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutcome")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer");

                    b.Property<string>("PlannedActivity")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("RolledOver")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SupportRequired")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("FocusAreas");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.MonthlyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionOfWork")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("KeyActivity")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer");

                    b.Property<string>("OutputResult")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("RolledOver")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.PerformanceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComplianceComment")
                        .HasColumnType("text");

                    b.Property<int?>("ComplianceRating")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionComment")
                        .HasColumnType("text");

                    b.Property<string>("InitiativeComment")
                        .HasColumnType("text");

                    b.Property<int?>("InitiativeRating")
                        .HasColumnType("integer");

                    b.Property<string>("Innovations")
                        .HasColumnType("text");

                    b.Property<string>("KeyAchievements")
                        .HasColumnType("text");

                    b.Property<string>("KeyChallenges")
                        .HasColumnType("text");

                    b.Property<string>("KnowledgeGained")
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("NewSkills")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverallRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("ProductivityComment")
                        .HasColumnType("text");

                    b.Property<int?>("ProductivityRating")
                        .HasColumnType("integer");

                    b.Property<string>("QualityOfWorkComment")
                        .HasColumnType("text");

                    b.Property<int?>("QualityOfWorkRating")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StaffSignOffDate")
                        .HasColumnType("date");

                    b.Property<string>("StaffSignatureName")
                        .HasColumnType("text");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupervisorGeneralComments")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SupervisorSignOffDate")
                        .HasColumnType("date");

                    b.Property<string>("SupervisorSignatureName")
                        .HasColumnType("text");

                    b.Property<string>("SupportRequired")
                        .HasColumnType("text");

                    b.Property<string>("TeamworkComment")
                        .HasColumnType("text");

                    b.Property<int?>("TeamworkRating")
                        .HasColumnType("integer");

                    b.Property<string>("ToolsLearned")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("StaffUserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.AppUser", b =>
                {
                    b.HasOne("PerformanceTracker.Api.Domain.AppUser", "SupervisorUser")
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SupervisorUser");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.FocusArea", b =>
                {
                    b.HasOne("PerformanceTracker.Api.Domain.PerformanceReport", "Report")
                        .WithMany("FocusAreas")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.MonthlyActivity", b =>
                {
                    b.HasOne("PerformanceTracker.Api.Domain.PerformanceReport", "Report")
                        .WithMany("Activities")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.PerformanceReport", b =>
                {
                    b.HasOne("PerformanceTracker.Api.Domain.AppUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PerformanceTracker.Api.Domain.AppUser", "StaffUser")
                        .WithMany("Reports")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewedByUser");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.AppUser", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("PerformanceTracker.Api.Domain.PerformanceReport", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("FocusAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
